### ISSUE TITLE
Import data feature

### ISSUE THREAD

**Issue by tranghaviet** [tranghaviet/co-authors-network-management#13]
add Import data feature use helpers method.
Ref: https://github.com/nguoinaodo/project3_import

Implement: Dũng
Support: Lưu

**Comment by vuducdung** [comment]
​
 co-authors-network-management-dev.rar
<https://drive.google.com/file/d/1eCiATwPq69JlnaAZU5GgJChTd17SokVb/view?usp=drive_web>
​

2017-11-22 23:03 GMT+07:00 Tráng Hà Viết <notifications@github.com>:
